name: Atualizar Cupons de Hora em Hora

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependências
        run: npm install axios cheerio

      - name: Executar script de extração
        run: node extrair.js

      - name: Salvar no repositório
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.json
          git commit -m "Cupons e regras atualizadas [skip ci]" || exit 0
          git push
